/*
 * Copyright (C) SilentAlice All rights reserved.
 * Author: SilentAlice <https://www.silentming.net>
 * Create:  Thu Jan 30 17:05:45 2020
 */
#include <plat/memory.h>

#include <arch/type.h>
#include <arch/section.h>

#include <alice/memory.h>

#define STE_KERNEL_DEF		(STE_RSRV_BITS | STE_DOMAIN(0) | (0x2 << STE_AP_SHIFT))
#define STE_ADDR(base, offset)	(((base >> STE_BASE_SHIFT) + offset) << STE_BASE_SHIFT)

__attribute__((__aligned__(SECTION_TABLE_ALIGN)))
uint32_t startup_table[4096] = {
	/* KERNEL_LOAD_PADDR is direct mapping (16M) */
	[(KERNEL_LOAD_PADDR >> 20) + 0] = STE_ADDR(KERNEL_LOAD_PADDR, 0) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 1] = STE_ADDR(KERNEL_LOAD_PADDR, 1) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 2] = STE_ADDR(KERNEL_LOAD_PADDR, 2) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 3] = STE_ADDR(KERNEL_LOAD_PADDR, 3) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 4] = STE_ADDR(KERNEL_LOAD_PADDR, 4) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 5] = STE_ADDR(KERNEL_LOAD_PADDR, 5) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 6] = STE_ADDR(KERNEL_LOAD_PADDR, 6) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 7] = STE_ADDR(KERNEL_LOAD_PADDR, 7) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 8] = STE_ADDR(KERNEL_LOAD_PADDR, 8) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 9] = STE_ADDR(KERNEL_LOAD_PADDR, 9) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 10] = STE_ADDR(KERNEL_LOAD_PADDR, 10) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 11] = STE_ADDR(KERNEL_LOAD_PADDR, 11) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 12] = STE_ADDR(KERNEL_LOAD_PADDR, 12) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 13] = STE_ADDR(KERNEL_LOAD_PADDR, 13) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 14] = STE_ADDR(KERNEL_LOAD_PADDR, 14) | STE_KERNEL_DEF,
	[(KERNEL_LOAD_PADDR >> 20) + 15] = STE_ADDR(KERNEL_LOAD_PADDR, 15) | STE_KERNEL_DEF,

	/* KERNEL_START_VADDR maps KERNEL_LOAD_PADDR (16M) */
	[(KERNEL_START_VADDR >> 20) + 0] = STE_ADDR(KERNEL_LOAD_PADDR, 0) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 1] = STE_ADDR(KERNEL_LOAD_PADDR, 1) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 2] = STE_ADDR(KERNEL_LOAD_PADDR, 2) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 3] = STE_ADDR(KERNEL_LOAD_PADDR, 3) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 4] = STE_ADDR(KERNEL_LOAD_PADDR, 4) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 5] = STE_ADDR(KERNEL_LOAD_PADDR, 5) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 6] = STE_ADDR(KERNEL_LOAD_PADDR, 6) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 7] = STE_ADDR(KERNEL_LOAD_PADDR, 7) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 8] = STE_ADDR(KERNEL_LOAD_PADDR, 8) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 9] = STE_ADDR(KERNEL_LOAD_PADDR, 9) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 10] = STE_ADDR(KERNEL_LOAD_PADDR, 10) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 11] = STE_ADDR(KERNEL_LOAD_PADDR, 11) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 12] = STE_ADDR(KERNEL_LOAD_PADDR, 12) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 13] = STE_ADDR(KERNEL_LOAD_PADDR, 13) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 14] = STE_ADDR(KERNEL_LOAD_PADDR, 14) | STE_KERNEL_DEF,
	[(KERNEL_START_VADDR >> 20) + 15] = STE_ADDR(KERNEL_LOAD_PADDR, 15) | STE_KERNEL_DEF,
};
